### ISSUE TITLE
Create a hook script for PositioNZ-PP server crashes

### ISSUE THREAD

**Issue by dnhansen50** [linz/linz-positionzpp-server#10]
Create a script triggered by a crash on the positionz-pp server to automatically create a Github issue that a crash has occurred, with details about the crash.

**Comment by ccrook** [comment]
Server implementation changed in AWS.  Does notify if processing job starts and doesn't finish.  If bernese processing fails (not crash) then generates a debug file jobid-bernese-data.zip in S3 bucket.
