### ISSUE TITLE
nzgd2000.csv output file provides NZVD2009 heights but calls them nzvd2016

### ISSUE THREAD

**Issue by ndonnelly** [linz/linz-positionzpp-server#12]
This file has a column labelled 'NZVD2016_height' but the value provided in the field is actually a NZVD2009 height. Note that the correct NZVD2016 value is available in the summary.txt file and email supplied to the user.

**Comment by ccrook** [comment]
@ndonnelly Already fixed in source code but had not been implemented on to server.  I have now updated the server configuration with the revised template for the NZGD2000 CSV file.
