### ISSUE TITLE
Add a note about which reference the SINEX file is in

### ISSUE THREAD

**Issue by paulagentle** [linz/linz-positionzpp-server#17]
The SINEX files have no record of what reference the solution is in terms of.  Might be useful to add it as a note

**Comment by ccrook** [comment]
@paulagentle Do you mean version of station coordinate models?  Just want to make sure I understand

**Comment by paulagentle** [comment]
Hi Chris, this not was from September 2017.  I think I was meaning reference frame - looking ahead we will be moving to ITRF2014 so we may not know if it is ITRF2008 or not. If we want the position to be traceable then it might be worth adding station coordinate model version as well.

**Comment by ccrook** [comment]
PCF updated by Dionne to fix this issue.  Installed today
