### ISSUE TITLE
Incorrect reference to ITRF2008 in PositioNZ-PP job output

### ISSUE THREAD

**Issue by sking16** [linz/linz-positionzpp-server#20]
Hello @ccrook I noticed that there is an incorrect reference to ITRF2008 in the Positionz-pp job output. Towards the end of the output there is reference to ITRF20008. See text below.

Reference stations:

  The following reference stations have been selected to process this mark.
  The horizontal and vertical fit represent how well the calculated
  baselines from the supplied mark to these reference stations fit their 
  ITRF2008 coordinates in the minimum constraints solution.

    Station distance (km)    Fit(mm)             ITRF20008 XYZ (metres)
                           Hor    Vrt         X            Y            Z
    LKTA        79.5       2.4   -2.3    -4646207.790  630972.501 -4310354.222
    METH        82.3       2.7    5.2    -4577296.786  677933.180 -4375630.279
    MQZG        27.5       3.9   -2.9    -4580569.789  590466.336 -4384379.682

Thanks
Scott

**Comment by ccrook** [comment]
Fixed in bf64ae9b755cfe68394fa28306c35a801a29dfdc.

Pending completion of LINZ service request 8941794
